version: "3"
networks:
  # 해당 도커 컴포즈로 실행한 컨테이너는 동일한 네트워크를 공유한다.
  backend_network:
# services에서는 여러개의 컨테이너를 생성할수 있습니다.
services:
  server:
    # 이미지 생성을 위해 해당 디렉토리에 있는 Dockerfile를 build한다.
    # docker-compose파일에 같은경로로 Dockerfile이 있을시 '.' 을 찍으면 된다.
    container_name: alon_server_main_production
    # 같은경로가 아닐시 상대경로로 지정해서 실행한다.
    build:
      context: ./
      dockerfile: Dockerfile.product
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
